### ISSUE TITLE
ModuleNotFoundError: No module named 'nco_lib'

### ISSUE THREAD

**Issue by vpozdnyakov** [TheLeprechaun25/NCOLib#1]
I tried to run an example from README, section USE. The error message is: ModuleNotFoundError: No module named 'nco_lib'.
To reproduce: https://colab.research.google.com/drive/1ArbTWXiqGymTpUj-C2junxxoO_wFe_x5?usp=sharing

**Comment by TheLeprechaun25** [comment]
Added the current path in the examples, it should work now:)
